Landing page gifs
DariaAzanovich/frontend-lab pull request #2
Opened 2021-08-12 11:38 UTC by DariaAzanovich

2021-08-12 12:15 UTC, qwaseras requested changes

2021-08-12 12:15 UTC, qwaseras commented on workflow/landing-page/index.html
>                          <div class="card">
Remove this cards from HTML and add them after loading data

2021-08-12 12:15 UTC, qwaseras commented on workflow/landing-page/sources/sctript.js
> +let url = new URL(`https://api.giphy.com/v1/gifs/search?q=${search}&api_key=${API_KEY}&limit=${cardsAmount}&offset=`);
move this variable definition into the uploadGifs method
or even create a separate method which accepts all needed params and returns an URL

2021-08-12 12:15 UTC, qwaseras commented on workflow/landing-page/sources/sctript.js
> +    await fetch(url)
dont use callback approach inside async func 
[Please read this](https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous/Async_await#%D0%BF%D0%B5%D1%80%D0%B5%D0%BF%D0%B8%D1%81%D1%8B%D0%B2%D0%B0%D0%B5%D0%BC_promises_%D1%81_%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC_asyncawait)

2021-08-12 13:58 UTC, DariaAzanovich commented on workflow/landing-page/sources/sctript.js
> +let cardText = '<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, deleniti, id quibusdam aut optio saepe soluta tempore neque voluptatum.</p>';
Not sure about this elements (they're same for each card)

2021-08-12 14:05 UTC, DariaAzanovich commented on workflow/landing-page/sources/sctript.js
> +const cardsAmount = 9;
What about masonry layout? Using flexbox it's needed to set max-height. If change cardsAmount all'll break

2021-08-13 08:11 UTC, qwaseras commented on workflow/landing-page/sources/sctript.js
> +let cardText = '<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, deleniti, id quibusdam aut optio saepe soluta tempore neque voluptatum.</p>';
It's ok, let it be

2021-08-16 13:34 UTC, qwaseras approved these changes

2021-08-16 13:34 UTC, merged